<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="83" started-at="2021-04-12T10:14:26 IST" finished-at="2021-04-12T10:14:26 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="83" started-at="2021-04-12T10:14:26 IST" finished-at="2021-04-12T10:14:26 IST">
      <class name="testgClasses.Demo2TestNg">
        <test-method status="PASS" signature="bt()[pri:0, instance:testgClasses.Demo2TestNg@4b4523f8]" name="bt" is-config="true" duration-ms="15" started-at="2021-04-12T10:14:26 IST" finished-at="2021-04-12T10:14:26 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bt -->
        <test-method status="FAIL" signature="testcase1()[pri:0, instance:testgClasses.Demo2TestNg@4b4523f8]" name="testcase1" duration-ms="10" started-at="2021-04-12T10:14:26 IST" finished-at="2021-04-12T10:14:26 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [tu] but found [hi]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [tu] but found [hi]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testgClasses.Demo2TestNg.testcase1(Demo2TestNg.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
      </class> <!-- testgClasses.Demo2TestNg -->
      <class name="testgClasses.Demo3Te">
        <test-method status="PASS" signature="testcase3()[pri:0, instance:testgClasses.Demo3Te@731a74c]" name="testcase3" duration-ms="2" started-at="2021-04-12T10:14:26 IST" finished-at="2021-04-12T10:14:26 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase3 -->
        <test-method status="PASS" signature="testcase2()[pri:1, instance:testgClasses.Demo3Te@731a74c]" name="testcase2" duration-ms="2" started-at="2021-04-12T10:14:26 IST" finished-at="2021-04-12T10:14:26 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2 -->
        <test-method status="PASS" signature="after()[pri:0, instance:testgClasses.Demo3Te@731a74c]" name="after" is-config="true" duration-ms="0" started-at="2021-04-12T10:14:26 IST" finished-at="2021-04-12T10:14:26 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- after -->
      </class> <!-- testgClasses.Demo3Te -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
